### ISSUE TITLE
BigInteger replacement

### ISSUE THREAD

**Issue by JohannesLichtenberger** [libj/math#31]
Hello,

as `BigInteger` creates a lot of garbage I'm searching for an alternative (used for hash computations (using 128 bit of a SHA256 for a rolling hash in a versioned JSON data store (https://Github.com/sirixdb/sirix))). How do I use your library? IIRC last time I tried the classes were missing from the JAR on maven central.

Kind regards
Johannes

**Comment by JohannesLichtenberger** [comment]
Thanks, can you add a constructor `BigInt(int signum, byte[] magnitude)`? I want to port 1:1 but maybe I missed something :)

**Comment by JohannesLichtenberger** [comment]
I've the following repos and I could get the JAR with Gradle:

```
    repositories {
        mavenCentral()
        maven {
            url = "https://oss.sonatype.org/content/repositories/snapshots/"
        }
        maven {
            url "https://kotlin.bintray.com/kotlinx"
        }
        mavenLocal()
    }
```

However, once compiling, I'm getting this strange error:

```
Execution failed for task ':sirix-core:compileJava'.
> Could not resolve all files for configuration ':sirix-core:compileClasspath'.
   > Could not resolve diff_match_patch:diff_match_patch:current.
     Required by:
         project :sirix-core > org.libj:math:0.6.7-SNAPSHOT:20220905.155224-52 > org.libj:util:0.9.0-SNAPSHOT:20220905.085345-103
      > Could not resolve diff_match_patch:diff_match_patch:current.
         > Could not get resource 'https://kotlin.bintray.com/kotlinx/diff_match_patch/diff_match_patch/current/diff_match_patch-current.pom'.
```

**Comment by JohannesLichtenberger** [comment]
I'd furthermore need something like this:

```java
          final BigInt bigInt = deserializeBigInteger(source);
          final int scale = source.readInt();
          number = Decimal.valueOf(bigInt, scale);
```

Before it was a BigDecimal, but I guess the default value is not the scale.

**Comment by safris** [comment]
@JohannesLichtenberger:
1. I don't explicitly support Gradle, so you're on your own there
2. It's not clear to me what "you need furthermore"

**Comment by JohannesLichtenberger** [comment]
Regarding 2. `BigDecimal` IIRC has a constructor with `BigInteger` as the first param and the scale as a second argument and once I'm back from holiday I'd like to finish my 1:1 port from the JDK classes to your replacement and compare performance with a JMH benchmark.

**Comment by safris** [comment]
@JohannesLichtenberger, I have not worked on the `Decimal` implementation in a while, and don't have the time right now to get back into it. If you want to propose a PR, I'll be open to it. Regarding "compare performance" -- [this is already implemented](https://github.com/libj/math/#benchmark-results-1). If you want to supplement with additional performance benchmarks, I'll be open to those PRs as well.
